services:
  - type: web
    name: bursary-saas
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bursary-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: DB_SSL
        value: "true"
databases:
  - name: bursary-db
    plan: free
